### ISSUE TITLE
Useful and pretty RESTful API autodocs

### ISSUE THREAD

**Issue by Tmpod** [HypixelDev/PublicAPI#130]
Hey there!
I'm currently developing an asynchronous Python wrapper for this API and I'm finding the documentation extremely bad since it essentially just gives you a little short description about some endpoints... It seems to lack at least one endpoint (see #104), it doesn't show all available params for at least the `guild` endpoint (namely, `name` and `player`) and it doesn't really tell you the structure of a response, including field types and optional fields. 
I don't know what lib(s) or even what language you're using for the server side but it's fairly simple to add auto-docs to any of the major server libs. Maybe consider using something like [Swagger](https://swagger.io)?
Either way, you should definitely improve these "docs" as they are used by a substancial amount of people, and after all, you're Hypixel, the biggest Minecraft server to have ever existed...
Cheers

**Comment by Tmpod** [comment]
If anyone is interested they can find `aiohypixel` [here](https://tmpod.gitlab.io/aiohypixel). I'm writing dataclasses to represent all data structures this API provides with full documentation. It may be useful for anyone trying to use API ig.

**Comment by Tmpod** [comment]
Also, Swagger would be nice as it would make the API follow the OpenAPI standard and make it more concise in stuff like naming cases and codenames.

**Comment by ConnorLinfoot** [comment]
A lot of data in the Hypixel API isn't strict in either response or type. There are some fields that will always be returned in a specific format but there is also a lot outside of this scope. This is due to us using an approach where data is served directly from database responses. 

Because of this documentation can easily become out of date. We prefer to go the route of giving basic information for developers to make the API requests and then analyze and use the data as they see fit.

**Comment by Tmpod** [comment]
mm weird design choice but ok, ig that's fair
