### ISSUE TITLE
[SkyBlock] Players sometimes wrongfully returned without any SkyBlock profiles

### ISSUE THREAD

**Issue by LeaPhant** [HypixelDev/PublicAPI#136]
Sometimes the `/player` endpoint doesn't return any SkyBlock profiles for the player even though they have one. At the beginning I thought this was only happening on co-op profiles but it's happening on solo profiles too.

Here's a UUID that's affected: 10f13cc2af02462986c5d4d20a2dc524.

`https://api.hypixel.net/player?uuid=10f13cc2af02462986c5d4d20a2dc524`

results in

```JS
"stats": {
    "SkyBlock": {
        "profiles": {}
    },
    // ...
}
```

...even though they have a profile you can visit:

![image](https://user-images.githubusercontent.com/14080165/67415844-094ece00-f5c6-11e9-8bf0-248fbf15e745.png)

**Comment by ConnorLinfoot** [comment]
This seems to be an issue that has affected players who have started playing since the profile update in September, where they haven't created any profiles outside of the default and it has resulted in it not being added to the list in the player data.

We have a fix pending roll for this, but even once live will require each player affected to join before it will appear. In the meantime, a workaround is that because the default profile is the same UUID as the player, you can use that to look up their profile for the time being. (https://api.hypixel.net/skyblock/profile?key=YOUR_KEY_HERE&profile=10f13cc2af02462986c5d4d20a2dc524)

Thanks for reporting this to us! 😃
