### ISSUE TITLE
More info about session endpoint removal

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#149]
Hello, I would like to get more info about session endpoint. It has been deprecated for a year and nothing seems to be going on about it.

First of all, when is this going to happen? Nothing really happened during this year of it being deprecated.

Second main question: will there be any backwards compatibility or will `/session` just return 404?
I would prefer it to either return an error:
```json
{
  "success": false,
  "cause": "This endpoint has been disabled."
}
```
or just a successful response with no session like this:
```json
{
  "success": true,
  "session": null,
  "warning": "This endpoint has been disabled."
}
```

Also, since sessions are quite useful, as you can see what game someone is playing, will there be any alternative for the session endpoint?

**Comment by ConnorLinfoot** [comment]
Sessions were created as an internal system and weren't designed for public use. We've seen more abuse over this endpoint and feel that it's best to remove it rather than maintain support for it.

We don't have an exact date of removal, it'll likely be sometime in the next few months. The endpoint will return a response similar to the first example you've provided, where success will be false.
