### ISSUE TITLE
Add the Ability to Sort Skyblock Auctions

### ISSUE THREAD

**Issue by cyandev** [HypixelDev/PublicAPI#152]
It would be very useful to have some feature that would allow us to sort skyblock auctions by price, duration remaining, etc. As of now I have to constantly make requests and only end up with a small fraction of completed auctions.

**Comment by puppy0cam** [comment]
It is intended for you to send multiple requests, use pagination and request all the pages available. Then, you can sort the results on your end.

**Comment by skyblockz** [comment]
Quote of hypixel devs: Dont be lazy :)

**Comment by ConnorLinfoot** [comment]
Yeah, the above points cover this. If you wish to store the data you should load all the entries and sort it within your project.

**Comment by Flachdachs** [comment]
The current mechanism is not very useful. To be able to give qualified answers I have to fetch all the $totalPages pages before I can start filtering and sorting. And this has to happen every time when the data needs a refresh. If I filter the data in the current state page by page, the user will see an arbitrary amount between 0 and $perPage items when going through the result sets, which is very weird UX. And sorting doesn't work, because sorting of only one page has no value for the user.

To make this API more useful either remove server side paging, i.e. give all data at once, or add both filtering and sorting.

However, in both cases a paged result set has the problem that the data source could be updated between requests and can result into duplicate or missing records.

**Comment by puppy0cam** [comment]
> However, in both cases a paged result set has the problem that the data source could be updated between requests and can result into duplicate or missing records.

All responses will include a lastUpdated field, if that does not match all other results, you should retry and try to time it to send the requests just after the next update is expected to happen.

**Comment by builder-247** [comment]
I'm working hard on adding auctions to the Slothpixel API, supporting filtering and even history, so waiting for that is an option.

**Comment by bchen290** [comment]
Isn't it less efficient to have our client hammer ten or so requests at the server everytime we want to update instead of having the server only to have to send a response once?

**Comment by jamin-bagel** [comment]
> Isn't it less efficient to have our client hammer ten or so requests at the server everytime we want to update instead of having the server only to have to send a response once?

For the client, pagination definitely can be a pain. If the server did start sending every auction at once though, that's roughly 23MB that would be returned with every request as opposed to the ≈100KB (max) that it normally has to send for other endpoints. Although pagination can be a client inconvenience, it would be way worse if the API servers themselves had to send over that much more data than usual, slowing things down for everyone.

**Comment by builder-247** [comment]
For those seeking this functionality this can now be achieved via the Slothpixel API: https://docs.slothpixel.me/#tag/skyblock
