### ISSUE TITLE
[SkyBlock Suggestion] Add the RNG-droprate-table to the API

### ISSUE THREAD

**Issue by doej1367** [HypixelDev/PublicAPI#222]
Is it possible to add a droprate table to api.hypixel.net/methods/resources/skyblock/?

It would be cool to know the exact droprate of every drop in the game.
I could finally be able to calculate how long it takes to get a specific drop,
and how much each RNG-drop is acually worth.

I am talking about e.g the pet droprates at their various rarity levels incl. the droprates from fishing and the different Enderman,
Droprates from special items like 'Shrimp the Fish' and data like that.

Thanks in advance :)

**Comment by puppy0cam** [comment]
As randomness is used in many places in the game, it would be an impossible task to document all of them in an agreed-upon format which can also stand the test of time. RNG values are likely hardcoded into the game anyway, so this would be a manual effort to keep it up to date.
Let's not forget that the RNG can be influenced by other means to make the game more enjoyable so that a streak of bad luck does not destroy you.
The game is far more stable if the exact odds are not known to the public. For example, if the drop rates changed for something you would see the game economy adjust instantly and players that were asleep or otherwise busy when it happened wouldn't have a chance to react.

**Comment by doej1367** [comment]
> RNG values are likely hardcoded into the game
I was afraid that this might be the case :/
Thanks for your answer. Suggestion discarded.
