### ISSUE TITLE
(Suggestion) Include usernames in responses (specifically for guilds)

### ISSUE THREAD

**Issue by Eqrly** [HypixelDev/PublicAPI#228]
**Example (Guild):**

``` guild.member
       
        "uuid": "fb84afcbdefe419a8584adf88483173e",
        "username": "Frogish",
        "rank": "Guild Master",
        "joined": 1515806281240,
        "questParticipation": 2332,
        "mutedTill": 0,
        "expHistory": {
          "2020-05-02": 88146,
          "2020-05-01": 103083,
          "2020-04-30": 170151,
          "2020-04-29": 140774,
          "2020-04-28": 37069,
          "2020-04-27": 93723,
          "2020-04-26": 103783
        }
      }
```

**Comment by puppy0cam** [comment]
It is better to obtain the information from the [player endpoint](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/player.md) or the [Mojang API](https://wiki.vg/Mojang_API). The username is rarely changed, and you can safely cache it for quite a while. Just don't try to use it for more than just visual display. The UUID is the single source of truth that you should be using to uniquely identify the player.
This information is most likely not returned because it is not stored within guild related data in the first place. The API tends to return data from the database in it's raw form (with redactions made intentionally) so this information is unlikely to be added.

**Comment by Flachdachs** [comment]
Why is it better to use the player endpoint? It returns a large amount of data that is not needed to get the player's name. You might argue that after adding the player's name as the most important information the next developer requests to also add e.g. lastLogin/lastLogout. OK, then it is really time to query the player endpoint. Not only because this is information you practically can't cache.

Using the player endpoint suffers from the limitation of 120 API requests per minute. For guilds larger than 119 members you have to delay the remaining requests for a minute. Additionally in this time you can't query other data.

The Mojang API also [has a problem](https://bugs.mojang.com/browse/WEB-1587), you can't query it from a browser.

**Comment by mdashlw** [comment]
Multiple api keys exist.
> Using the player endpoint suffers from the limitation of 120 API requests per minute. For guilds larger than 119 members you have to delay the remaining requests for a minute. Additionally in this time you can't query other data.

Query on backend?
> The Mojang API also has a problem, you can't query it from a browser.

And anyway usernames are not returned because they are not stored in guilds and there is probably no reason for hypixel to store it, because you have to maintain it in case name changes, so it's not getting added.

**Comment by Flachdachs** [comment]
> Multiple api keys exist.

Only one per Minecraft account. If it is intended to spread the traffic using multiple accounts then the easier solution would be to raise the query limit.

> Query on backend?

There is GDPR and other privacy laws. In my case I don't want to be able to track the users. They should query data on their own behalf.

> And anyway usernames are not returned because they are not stored in guilds and there is probably no reason for hypixel to store it, because you have to maintain it in case name changes, so it's not getting added.

Joins and correlated subqueries exist.

**Comment by mdashlw** [comment]
Still if it's not here already, then hypixel doesn't need it and it won't get added

**Comment by ConnorLinfoot** [comment]
The above regarding querying and caching usernames is the correct approach here.
