### ISSUE TITLE
Plans on removing 'name' parameter from /player?

### ISSUE THREAD

**Issue by TheNullicorn** [HypixelDev/PublicAPI#249]
The player endpoint's `name` parameter has been deprecated for 4 years now ([blame](https://github.com/HypixelDev/PublicAPI/blame/master/Documentation/methods/player.md)). Are there any plans on actually removing it, because I don't see any reason to.

**Comment by mdashlw** [comment]
I don't see why would it be removed, even though it's deprecated. That's a big breaking change

**Comment by TheNullicorn** [comment]
If anyone is using `name`, then that's on them for using a deprecated parameter. Still, the only reason I see for removing it is that the API stores an outdated username, although that rarely seems to be an issue anyways.

**Comment by Plancke** [comment]
We're using a sharded Mongo setup, with a player's UUID as the key. This means that any query that doesn't use the UUID, these "by name" requests, has to send the query to every single shard in order to find the document. Right now it's not causing issues, but it's possible that it could in the future so we deprecated it way back then to prevent people from relying on it.

As @TheNullicorn mentioned as well, these usernames may be outdated with Mojang because they haven't logged in since the name change. We do return the most recently logged in user if there are 2 with the same name on our end but this should also not be relied upon.

The [Mojang API](https://wiki.vg/Mojang_API) has a name lookup API at a given timestamp or a bulk up to 10 name lookup. It's recommended to use these instead.
