### ISSUE TITLE
[Suggestion] Create a new endpoint for stats, separate from /player

### ISSUE THREAD

**Issue by alfie1706** [HypixelDev/PublicAPI#261]
Hello!

As a developer using the API semi-frequently, I believe that the gamemode stats should have its own endpoint with an additional parameter to choose the gamemode. As this is added, the stats in the /player endpoint could be slowly phased out. This would allow the newly added /stats endpoint to be more organised, even sorting games such as bedwars into their respective stat types; Overall, Eight_One etc...

I would love to hear other opinions on something similar to this!

**Comment by WolfDWyc** [comment]
I completely agree. For most uses, the current endpoint returns an absurdly giant JSON, it would be great to have stats more organized and easy to manage.
However, if this is implemented, please make sure to keep some endpoint that still gives all the stats, for the times it IS needed, and for people already using it that don't want to switch to the new endpoints.

**Comment by AnotherZane** [comment]
The current `/player` endpoint is a complete mess. Hopefully doing this will fix issues like random spaces and extra underscores in the json.

**Comment by TheNullicorn** [comment]
The problem is that they don't use models anywhere; everything is completely flexible. Whenever one of their devs writes a new minigame, lobby feature, etc that uses the database, it seems they create a new field wherever they please and call it a day. Because of this, you end up with all sorts of garbage on the main player object like the leveling rewards flags:

![Screen Shot 2020-06-12 at 9 24 23 PM](https://user-images.githubusercontent.com/64789500/84556810-338b0280-acf3-11ea-82aa-63be321436d0.png)

They store data in a way that only the developer working with that specific data can read, and as a result, the API response is full of undocumented garbage data. As much as I would love more organized data endpoints, it seems that any time they're asked to do preprocessing on their end (which this would take *a lot* of), the idea is rejected.

It seems like even they know how bad the player endpoint is because it's the only API response in the Java API [represented by a JsonObject instead of an actual class](https://github.com/HypixelDev/PublicAPI/blob/968839bfb86b1ca66f2148ce22044dd06200e006/Java/src/main/java/net/hypixel/api/reply/PlayerReply.java#L7). However, they have millions of documents worth of players, so I don't see this ever being fixed.

**Comment by ConnorLinfoot** [comment]
This would require extra processing on our end. We don't have plans to change this at this time.

**Comment by cryy** [comment]
> 
> 
> This would require extra processing on our end. We don't have plans to change this at this time.

you don't care about performance and you know it - this won't be implemented simply because they don't want to implement it.

**Comment by TheNullicorn** [comment]
> > This would require extra processing on our end. We don't have plans to change this at this time.
> 
> you don't care about performance and you know it - this won't be implemented simply because they don't want to spend time implementing it.

We should be thankful that they provide a public API– most big networks don't have that. With the massive success of SkyBlock, I'm certain they have much higher priorities right now than this little side-project. There's no need to attack any of the devs for being busy with more important things.

**Comment by cryy** [comment]
> 
> 
> > > This would require extra processing on our end. We don't have plans to change this at this time.
> > 
> > 
> > you don't care about performance and you know it - this won't be implemented simply because they don't want to spend time implementing it.
> 
> We should be thankful that they provide a public API– most big networks don't have that. With the massive success of SkyBlock, I'm certain they have much higher priorities right now than this little side-project. There's no need to attack any of the devs for being busy with more important things.

if they're not going to bother maintaining the API and keeping it usable, why have it there in the first place? they have priorities, yes, however that was not the reason to close this issue, it's a well known fact that hypixel's API is a dumpster fire and should be rewritten - or at least improved on.

i'm not attacking anyone, i'm calling out a generic response instead of actually saying why they won't be implementing it.

this project depends a lot on community contribs. i don't doubt for a second it's the reason for the repo is public and i appreciate the work

**Comment by mdashlw** [comment]
Player model is a complete mess, nobody denies that. But I'm pretty sure this won't ever get changed, because it's a lot of work and there are millions of player documents. Changing code everywhere in all projects, migrating millions of documents world require a significant amount of money to pay devs. But for normal player there won't be any visible changes, so it's not worth it, that's how enterprise works.

**Comment by alfie1706** [comment]
> Player model is a complete mess, nobody denies that. But I'm pretty sure this won't ever get changed, because it's a lot of work and there are millions of player documents. Changing code everywhere in all projects, migrating millions of documents world require a significant amount of money to pay devs. But for normal player there won't be any visible changes, so it's not worth it, that's how enterprise works.

This isn't what this Suggestion is regarding, we're not asking for the /player endpoint to be changed _yet_, I'm asking that they add a NEW /stats endpoint, this would mean that when they next work on game modes they can move them over to the new endpoint and external developers using the API would have ample time to be able to make the switch from /player to /stats. After everything server-side has been moved over from /player to /stats, then they could begin to phase out the stats being shown in the /player endpoint.

**Comment by AnotherZane** [comment]
> > Player model is a complete mess, nobody denies that. But I'm pretty sure this won't ever get changed, because it's a lot of work and there are millions of player documents. Changing code everywhere in all projects, migrating millions of documents world require a significant amount of money to pay devs. But for normal player there won't be any visible changes, so it's not worth it, that's how enterprise works.
> 
> This isn't what this Suggestion is regarding, we're not asking for the /player endpoint to be changed _yet_, I'm asking that they add a NEW /stats endpoint, this would mean that when they next work on game modes they can move them over to the new endpoint and external developers using the API would have ample time to be able to make the switch from /player to /stats. After everything server-side has been moved over from /player to /stats, then they could begin to phase out the stats being shown in the /player endpoint.

It would be better to start do something like this now, cause eventually it'll get to a point where the /player endpoint will just not be viable to use anymore
