### ISSUE TITLE
[question] How to make sense of the 'data' in the skyblock profiles

### ISSUE THREAD

**Issue by MeijeronFire** [HypixelDev/PublicAPI#318]
In the skyblock api, in the /skyblock/profiles area, to get inventory contents, enderchest contents etc, there is a huge string which I cannot make any sense of. Does anyone know how to use this? thanks.

**Comment by TheNullicorn** [comment]
In case anyone stumbles upon this issue in the future...

`data` fields contain NBT data that is gzipped and base64-encoded (in that order). This means that to read it, you will need to do the reverse:
1. Decode the base64 into your language's equivalent of a byte/int8 array
2. Decompress the data using gzip (e.g. Java's [GZIPInputStream](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPInputStream.html))
3. Use an NBT parsing library to convert the NBT binary to a readable format (e.g. a Map, JavaScript object, etc)

Any good NBT parsing library should do steps 2 and 3 for you, since gzip is very commonly used to compress NBT data.
