### ISSUE TITLE
Api Problems

### ISSUE THREAD

**Issue by WeirdMango** [HypixelDev/PublicAPI#331]
Dear Fellow hypixel api ppl
I'm gonna go right to da chase,
There is a way to make your hypixel join date unknown and I think you can stop it.
If you get an account that's never logged onto hypixel and has no special permissions or advantages
If you buy a rank for an account that's never logged on before and then you log on with the rank. if you search on the api it'll tell you that the firstlogin is unknown, if you never log into the server with your rank both of your firstlogin/last login will be unknown
How to fix this:
I don't know java that well, im a python geek but I think if hypixel developers could change the way on the store so that it checks if they've ever logged in.
This can also help if somebody buys a rank for the wrong account and just overall prevent any misuse
There are currently hundreds (to my knowledge) that I have found, one of my favorites being Quadrilaterals as you perfectly can see their stats showcased except the joindate is unknown
Why does this happen?
Honestly I'm not even sure to the slightest bit, if I had to take a guess it'd probably be when the rank is given to the player maybe it does something differently then when somebody just joins the server
I'm not that good with java, i just hope i can help
Have a great day!

**Comment by mdashlw** [comment]
This is because the store creates a player document with the least fields possible and attaches purchased packages to it, while logging in for the first time properly populates it with fields like `firstLogin`.
I'm not sure of a solution to this, maybe the store could add `"partial": true"` to the document, and when logging it, the server would check this field and act as if it was first login and do all sorts of things.

Workaround for other api users: you can extract timestamp from `_id` which is mongodb object id and use that as first login.

**Comment by ConnorLinfoot** [comment]
The above is correct basically, you can get the time from the mongo ID or handle the player not having any further data due to not yet joining the server.
