### ISSUE TITLE
Requests blocked by Cloudflare (error code 1020)

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/PublicAPI#393]
Yesterday all requests to the api started to fail with cloudflare error code 1020 out of nowhere. Afaik 1020 is when it detects some suspicious activity, i.e. it responds 1020 when you are trying to access a website with "I'm Under Attack Mode" (5 seconds waiting thing).
I'm not sure whether Cloudflare behind the api is intended or not, but either way I'm doing no more than 200 requests/min (upper bound) so this is clearly a false positive.
 Please take action as soon as possible. It's been more than 24 hours, this is causing huge inconvenience to my bot.

**Comment by ConnorLinfoot** [comment]
We use Cloudflare to enforce specific rules when users abuse our services, usually, these blocks are due to excessive requests to other endpoints on our domain. I'm unable to check this situation due to no specific information being provided, but these blocks usually last 48 hours.

If you have any other questions or concerns with this, I would advise you to go through our support channels https://support.hypixel.net

**Comment by mdashlw** [comment]
> 
> If you have any other questions or concerns with this, I would advise you to go through our support channels https://support.hypixel.net

48 hours have passed so it's fine now, but what would be the point of contacting support if it takes 2 weeks to get a response while blocks last for 2 days?
