### ISSUE TITLE
Challenges Endpoint returns completely different value than when using a bot

### ISSUE THREAD

**Issue by tmgkopczyk** [HypixelDev/PublicAPI#571]
Hypixel API challenge amount via Statsify: https://imgur.com/a/ET26xKl

Hypixel API challenge amount via HTTPS: 19

**Comment by Picsou993** [comment]
Hi, Statsify is using the achievement value for the total challenges. You can get it under `player.achievements.general_challenger`.

The 19 you are getting is by doing the sum of all of its challenges (it the case of xPickaxeTubeHDx he has only done the challenge BEDWARS__support 19 times).

If I remember correctly, challenges were initially tracked only in the achievement field and not one by one too. So that's why there can be a difference between these 2 values.

And so it's not an API bug.
