### ISSUE TITLE
IP Whitelist is not working

### ISSUE THREAD

**Issue by Komas19-new** [HypixelDev/PublicAPI#632]
So, my personal app for an Discord Bot got approved, and i wanted to limit the usage to only the machine that hosts my bot, so i saw that you can put an IP whitelist, so i put the machine's whitelist in, and it doesn't do anything, i can still do a request myself from my computer and i don't get blocked.

I have other people that are seeing the same bug happend: https://hypixel.net/threads/api-ip-whitelist-doesnt-seem-to-work.5627625/ (made by me)

**Comment by ConnorLinfoot** [comment]
It doesn't look like your application has an IP whitelist set, make sure you are adding the IP address by clicking the checkmark on the right of the input field as seen in the example below. I'm unable to reproduce any issues and the whitelist works accordingly.

![image](https://github.com/HypixelDev/PublicAPI/assets/540942/072d96f5-60e0-41c7-88fa-854b80ff6867)

**Comment by Mqlvin** [comment]
> It doesn't look like your application has an IP whitelist set, make sure you are adding the IP address by clicking the checkmark on the right of the input field as seen in the example below. I'm unable to reproduce any issues and the whitelist works accordingly.

Hi Connor

I did some testing myself, as this issue was brought up to me via the forum thread Komas19-new made.

I've repeatedly tried to add my IP to the whitelist - I can add it, press apply changes and I get the little green notification pop-up saying "Whitelist updated!". Immediately pressing back on the "Manage whitelist" button shows my IP in the box. As far as that goes it all seems okay. However, on page reload, pressing "Manage whitelist" no longer shows my IP in the box, as if the IP was not actually applied.

Despite this, I still assumed backend everything was fine and tested the whitelist as if it had applied successfully. However since having applied the whitelist, I've been able to make requests from a non-whitelisted IP multiple times, and still can now 3 days after the whitelist has been applied.

I'm assuming the whitelist doesn't take 3+ to come into effect, so could it be possible your backend isn't saving/applying the IP inputted by the users?

**Comment by Komas19-new** [comment]
> It doesn't look like your application has an IP whitelist set, make sure you are adding the IP address by clicking the checkmark on the right of the input field as seen in the example below. I'm unable to reproduce any issues and the whitelist works accordingly.
> 
> ![image](https://private-user-images.githubusercontent.com/540942/318113201-072d96f5-60e0-41c7-88fa-854b80ff6867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MjA2NTUsIm5iZiI6MTcxMTgyMDM1NSwicGF0aCI6Ii81NDA5NDIvMzE4MTEzMjAxLTA3MmQ5NmY1LTYwZTAtNDFjNy04OGZhLTg1NGI4MGZmNjg2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQxNzM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjkwZDFkOGEzODQzOThlNTVhYjI1YzkyMGY5NWMzMTU2MDhkMzdhZDBhOGNiZjVmZTJjOGJmNDc2MjdiNTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U4WcVU9F93-2EPy6HZRAZNkwqqDgyQkHuQgZMuW_BGs)

i did that and it still doesn't work.. gonna try on a different browser

**Comment by Komas19-new** [comment]
turns out the browser is the issue, i was using LibreWolf 124

**Comment by Mqlvin** [comment]
> turns out the browser is the issue, i was using LibreWolf 124

Can you confirm if the whitelist does in fact work now? From my testing it still doesn't work and I'm on the latest version of Chromium.

**Comment by Komas19-new** [comment]
> > turns out the browser is the issue, i was using LibreWolf 124
> 
> Can you confirm if the whitelist does in fact work now? From my testing it still doesn't work and I'm on the latest version of Chromium.

![image](https://github.com/HypixelDev/PublicAPI/assets/82937056/9724f878-611d-4235-b49b-ed2eba9293b1)

yeah, it works now for me, try it with Microsoft Edge, thats how i managed to do it
