### ISSUE TITLE
Museum level experience doesn't match museum rewards

### ISSUE THREAD

**Issue by MattTheCuber** [HypixelDev/PublicAPI#641]
## Issue
If you go to your SkyBlock leveling breakdown and check Museum Donations, then go to your Museum Rewards and sum the total experience gained and sum the total possible (max) experience, they do not match.

## Proof
![image](https://github.com/HypixelDev/PublicAPI/assets/32849887/6cd393ad-a8c6-4885-b8b9-b9b75045ded2)

![image](https://github.com/HypixelDev/PublicAPI/assets/32849887/a3c3e405-f929-49fa-9d98-41fe0947853a)

I have triple checked that I am summing correctly in code and manually in a spreadsheet.

P.S. Let me know if this issue does not fit in this repo and I can move it to the Hypixel SkyBlock Bug Reports forum (although they have fixed 0 bugs like this that I have reported in the past lol).

**Comment by ConnorLinfoot** [comment]
I don't have enough knowledge about the museum to give any response here on this, unfortunately. The only thing I could imagine being the issue at a quick glance would be if the museum rewards aren't claimed then they won't count towards the XP task.

But yeah, these sorts of issues should be reported at https://hypixel.net/bug-reports/create. These issues are usually low priority though, or more complicated to resolve due to how code in the game uses the data. I would also make sure to include further information about the suspected issue, such as the profile you are comparing and how you calculate

**Comment by MattTheCuber** [comment]
Thanks for the response Connor! Yeah, I kind of figured that may be the case. I will create a report in the forums.

P.S. To answer a few of those questions (although they don't matter): I have claimed all the rewards, it's my Strawberry profile (IGN: MattTheCuber), and the calculation used was simply scrolling through all the rewards and summing the SkyBlock XP gains.
