### ISSUE TITLE
Incorrectly Named games in the Resources Endpoint

### ISSUE THREAD

**Issue by stuffyerface** [HypixelDev/PublicAPI#656]
The games resources API Endpoint (/v2/resources/games) contains some games whose "name" field (.games.GAMEID.name) is inconsistent with how it is referred to in game.

"PIT" is named "Pit" instead of "The Pit" as it is called in game.
"PAINTBALL" is named "Paintball" instead of "Paintball Warfare" as it is called in game.
"WALLS" is named "Walls" instead of "The Walls" as it is called in game.

**Comment by TheNullicorn** [comment]
For end users, you should probably be mapping [each game's `databaseName`](https://api.hypixel.net/#section/Introduction/GameTypes) to your own names anyway since the API only returns english names. Then if you're missing a `databaseName` (ie a new game just got added) you can use the `name` field as a fallback and log a warning for yourself to add the new game's name.

**Comment by ConnorLinfoot** [comment]
All the names you have provided are correct to their names as used internally, we do have some games that may have different versions of names (we refer to them as "fancy names") but we only have standard names defined in the resource.
