### ISSUE TITLE
Method to return the # of people in a gamemode.

### ISSUE THREAD

**Issue by Kbz2001** [HypixelDev/PublicAPI#71]
Can you implement a series of methods that returns the current number of people in a specific gamemode? Sorry if this seems kind of random :P! I want to use these values for a Discord Bot.

**Comment by Dance-Dog** [comment]
_(I know I quit but what the heck)_
The admins do have a **gameCounts** method likely for internal purposes/tracking data, however with some guidance from Nivyox I did manage to create a workaround.

I don't want to tell you exactly how to make it (also considering yours appears to be in java and mine was in JS), but I'll tell you what you need to do:

•Login to Hypixel with the Minecraft Protocol
•Set an interval of time to update & store the player counts per game
•When you warp to a lobby for each check, fetch all of the entities and look for the armor stand at the X and Z of the desired game's NPC
•Store that data somewhere so that you can use it until the next check
•Warp to limbo upon connecting and after each check

**Comment by Plancke** [comment]
Added with https://github.com/HypixelDev/PublicAPI/pull/83
